---
zabbix:
  user: smg25
  pass: s4tH)vCbMf
  server: https://watchtower.decathlonin.net/zabbix
  https-verify: true

cachet:
  token: b730X5FsV5J3wTGowujo
  server: http://10.27.7.211/
  https-verify: false

settings:
  # IT Service which will be a root for Cachet Components
  # Leave it empty if you want to use /
  root_service: ''

  # How often check Zabbix for new incidents
  update_inc_interval: 10  # in seconds
  # How often check Zabbix for new IT Services
  update_comp_interval: 10  # in seconds


  # Log level https://docs.python.org/3.4/library/logging.html#levels
  log_level: CRITICAL
  # Additional logging level for requests module
  log_level_requests: CRITICAL

# Templates for incident displaying
# Fill free to use Markdown
templates:
  # Template for acknowledgements (acknowledgement)
  # Supported fields:
  #   message: acknowledgement msg
  #   ack_time: acknowledgement time
  #   author: First name + Surname of Zabbix user
  acknowledgement: |
    {message}
    ###### {ack_time} by {author}
    ______

  # Template for new incinents (investigating)
  # Supported fields:
  #   group: Cachet Group
  #   component: Cachet Component
  #   time: Zabbix event time
  #   trigger_name: Zabbix trigger name
  #   trigger_description: Zabbix trigger description (comment)
  investigating: |
    {group} | {component} check **failed** - {time}

    ```{trigger_name}```

  # Template for resolved incinents (resolving)
  # Supported fields:
  #   time: Incindent resolved time in Cachet
  resolving: |
    __Resolved__ - {time}
    ______
